version: '2.3'

services:

  api:
    build:
      context: ""
      dockerfile: '${dockerfile}'
    image: '${image_name}'
    ports:
      - '${api_port}:8000'
    volumes:
      - '.:/opt/denzel'
    command: gunicorn -b 0.0.0.0:8000 app:app
    environment:
      - GUNICORN_CMD_ARGS="--timeout=600"  # 10 minutes
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  denzel:
    image: '${image_name}'
    runtime: '${runtime}'
    volumes:
      - '.:/opt/denzel'
      - './logs:/opt/denzel/logs'
    command: celery -A app.tasks worker --loglevel=info --logfile=logs/worker%i.log -n worker%${project_name}
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  redis:
    image: '${redis_image_tag}'

  monitor:
    image: '${image_name}'
    ports:
      - '${monitor_port}:5555'
    volumes:
      - '.:/opt/denzel'
    command: flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - api
      - redis
